//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Area()
        {
            this.AreaRelations = new HashSet<AreaRelation>();
            this.AreaRelations1 = new HashSet<AreaRelation>();
            this.ArticleRelations = new HashSet<ArticleRelation>();
            this.Embassies = new HashSet<Embassy>();
            this.Metroes = new HashSet<Metro>();
            this.Properties = new HashSet<Property>();
            this.ComplexBlogs = new HashSet<ComplexBlog>();
        }
    
        public int AreaID { get; set; }
        public string AreaName { get; set; }
        public int AreaOrder { get; set; }
        public string AreaDescription { get; set; }
        public string AreaSlug { get; set; }
        public string AreaNameInPersian { get; set; }
        public string AreaSeoTitle { get; set; }
        public Nullable<long> MapID { get; set; }
        public string ImageSmall { get; set; }
        public string ImageBig { get; set; }
        public Nullable<long> ImageSmallUploadID { get; set; }
        public Nullable<long> ImageBigUploadID { get; set; }
        public string TrafficCongestion { get; set; }
        public int FixedPropertyPrice { get; set; }
        public string Villa { get; set; }
        public string Office { get; set; }
        public string Climate { get; set; }
        public string WelfareAmenities { get; set; }
    
        public virtual Map Map { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AreaRelation> AreaRelations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AreaRelation> AreaRelations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticleRelation> ArticleRelations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Embassy> Embassies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Metro> Metroes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Property> Properties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComplexBlog> ComplexBlogs { get; set; }
    }
}
