//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreaRelation
    {
        public int AreaRelationID { get; set; }
        public int AreaID1 { get; set; }
        public int AreaID2 { get; set; }
        public int RelationOrder { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Area Area1 { get; set; }
    }
}
