//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleRelation
    {
        public int ArticleRelationID { get; set; }
        public int ArticleID { get; set; }
        public int ArticlePropertyOrder { get; set; }
        public System.DateTime InsertDate { get; set; }
        public Nullable<int> AreaID { get; set; }
        public Nullable<int> EmbassyID { get; set; }
        public Nullable<long> PropertyID { get; set; }
        public Nullable<int> PropertyTypeID { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Article Article { get; set; }
        public virtual Embassy Embassy { get; set; }
        public virtual PropertyType PropertyType { get; set; }
        public virtual Property Property { get; set; }
    }
}
