//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Blog()
        {
            this.ComplexBlogs = new HashSet<ComplexBlog>();
        }
    
        public long BlogID { get; set; }
        public string BlogSlug { get; set; }
        public string BlogTitle { get; set; }
        public string BlogBody { get; set; }
        public string BlogImageAddress { get; set; }
        public string BlogSubTilte { get; set; }
        public string BlogImageAddressSmall { get; set; }
        public Nullable<System.DateTime> InsertDateTime { get; set; }
        public int DisplayLanguageID { get; set; }
        public bool IsBlogNormal { get; set; }
        public bool BlogIsDraft { get; set; }
        public int BlogOrder { get; set; }
    
        public virtual DisplayLanguage DisplayLanguage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComplexBlog> ComplexBlogs { get; set; }
    }
}
