//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplexBlog
    {
        public long ComplexBlogID { get; set; }
        public int BlogTypeID { get; set; }
        public long BlogID { get; set; }
        public Nullable<long> MapID { get; set; }
        public Nullable<int> AreaID { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual BlogType BlogType { get; set; }
        public virtual Map Map { get; set; }
        public virtual Blog Blog { get; set; }
    }
}
