//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactU
    {
        public long ContactUsID { get; set; }
        public string ContactUsName { get; set; }
        public string ContactUsEmail { get; set; }
        public string ContactUsMessage { get; set; }
        public Nullable<System.DateTime> ContactUsDate { get; set; }
    }
}
