//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerBuy
    {
        public long CustomerBuyID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerEmail { get; set; }
        public string CustomerPhone { get; set; }
        public Nullable<System.DateTime> FirstCallDate { get; set; }
        public string AboutCustomer { get; set; }
        public string CustomerCountryFrom { get; set; }
        public string CustomerNation { get; set; }
        public bool CustomerHasBuyed { get; set; }
        public Nullable<long> PropertyID { get; set; }
        public Nullable<System.DateTime> BuyDate { get; set; }
        public Nullable<long> BuyPrice { get; set; }
        public Nullable<long> WhatAmountIsForUs { get; set; }
        public string CustomerBudget { get; set; }
        public string CustomerProcess { get; set; }
        public Nullable<System.DateTime> CustomerNextTimeToAction { get; set; }
        public string CustomerNextAlertToEmail { get; set; }
    }
}
