//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DirectMessage
    {
        public System.Guid DirecMessageID { get; set; }
        public System.DateTime DirecMessageInsertDate { get; set; }
        public string DirecMessageShortTitle { get; set; }
        public string DirecMessageTitle { get; set; }
        public string DirecMessageDataModel { get; set; }
        public string DirecMessageEmailTo { get; set; }
        public string DirecMessageSubject { get; set; }
        public bool DirecMessageIsBulk { get; set; }
        public byte DirecMessageStatus { get; set; }
        public byte DirecMessagePriority { get; set; }
        public byte DirecMessageEmailTry { get; set; }
        public bool DirecMessageEmailSent { get; set; }
        public byte EmailLayoutID { get; set; }
        public bool DirectMessageForceEmail { get; set; }
        public System.DateTime DirectMessageExpire { get; set; }
        public string DirectMessageEmailHtml { get; set; }
        public string DirectMessageEmailReason { get; set; }
        public Nullable<System.DateTime> DirectMessageEmailSentDate { get; set; }
    
        public virtual EmailLayout EmailLayout { get; set; }
    }
}
