//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountChange
    {
        public long DiscountChangeID { get; set; }
        public long CourseID { get; set; }
        public byte DiscountChangeTeacherOld { get; set; }
        public byte DiscountChangeTeacherNew { get; set; }
        public byte DiscountChangeTeacherCountNew { get; set; }
        public byte DiscountChangeTeacherCountOld { get; set; }
        public System.DateTime DiscountChangeCreateDate { get; set; }
    }
}
