//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Email()
        {
            this.EmailMarketingSends = new HashSet<EmailMarketingSend>();
            this.SendInEmails = new HashSet<SendInEmail>();
        }
    
        public long EmailID { get; set; }
        public byte EmailType { get; set; }
        public string EmailCustomBody { get; set; }
        public System.DateTime EmailInsertDateTime { get; set; }
        public int EmailStatus { get; set; }
        public string EmailLayout { get; set; }
        public string EmailTitle { get; set; }
        public bool EmailIsBulk { get; set; }
        public string CreatorUserID { get; set; }
        public string CourseDetail { get; set; }
        public Nullable<long> DiscountCodeStringID { get; set; }
        public Nullable<byte> EmailLayoutID { get; set; }
        public string EmailSubject { get; set; }
        public Nullable<long> GetUsersFromOtherEmail { get; set; }
        public System.DateTime EmailMustSentUnitll { get; set; }
        public long NumberOFSent { get; set; }
        public long NumberOfSeen { get; set; }
        public long NumberOfLinkClick { get; set; }
        public byte EmailPriority { get; set; }
        public long NumberEmailMustSend { get; set; }
        public int EmailCreateStatus { get; set; }
        public string SendEmailTestTo { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual EmailLayout EmailLayout1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailMarketingSend> EmailMarketingSends { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SendInEmail> SendInEmails { get; set; }
    }
}
