//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailLayout
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmailLayout()
        {
            this.DirectMessages = new HashSet<DirectMessage>();
            this.Emails = new HashSet<Email>();
            this.EmailMarketingSends = new HashSet<EmailMarketingSend>();
        }
    
        public byte EmailLayoutID { get; set; }
        public string EmailLayoutName { get; set; }
        public string EmailLayoutEnName { get; set; }
        public byte EmailLayoutCourseMax { get; set; }
        public string EmailLayoutDescription { get; set; }
        public int ViewOrder { get; set; }
        public bool IsActive { get; set; }
        public string EmailLayoutLayout { get; set; }
        public string EmailLayoutBody { get; set; }
        public byte EmailLayoutPriority { get; set; }
        public string unsubscribeUrl { get; set; }
        public string EmailLayoutTxt { get; set; }
        public bool EmailForceToNotConfirm { get; set; }
        public byte EmailSendPriority { get; set; }
        public bool EmailForceToUnsubscibed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DirectMessage> DirectMessages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Email> Emails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailMarketingSend> EmailMarketingSends { get; set; }
    }
}
