//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailMarketingSend
    {
        public System.Guid EmailMarketingSendID { get; set; }
        public System.DateTime EmailMarketingSendInsertDate { get; set; }
        public string EmailMarketingSendShortTitle { get; set; }
        public string EmailMarketingSendTitle { get; set; }
        public string EmailMarketingSendDataModel { get; set; }
        public string EmailMarketingSendEmailTo { get; set; }
        public string EmailMarketingSendSubject { get; set; }
        public bool EmailMarketingSendIsBulk { get; set; }
        public byte EmailMarketingSendStatus { get; set; }
        public byte EmailMarketingSendPriority { get; set; }
        public byte EmailMarketingSendEmailTry { get; set; }
        public bool EmailMarketingSendEmailSent { get; set; }
        public byte EmailLayoutID { get; set; }
        public bool EmailMarketingSendForceEmail { get; set; }
        public System.DateTime EmailMarketingSendExpire { get; set; }
        public string EmailMarketingSendHtmlPath { get; set; }
        public Nullable<System.DateTime> EmailMarketingSendEmailSentDate { get; set; }
        public bool EmailMarketingSendIsEmailMarketing { get; set; }
        public Nullable<long> EmailID { get; set; }
        public string UserID { get; set; }
    
        public virtual Email Email { get; set; }
        public virtual EmailLayout EmailLayout { get; set; }
    }
}
