//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailBlock
    {
        public long EmailBlockID { get; set; }
        public Nullable<long> EmailUnsubscribeID { get; set; }
        public System.DateTime InsertDate { get; set; }
        public string EmailBlockDescription { get; set; }
        public string EmailBlockFrom { get; set; }
        public string TheEmail { get; set; }
        public bool IsByUs { get; set; }
    
        public virtual EmailUnsubscribe EmailUnsubscribe { get; set; }
    }
}
