//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmbassyProperty
    {
        public long EmbassyPropertyID { get; set; }
        public int EmbassyID { get; set; }
        public long PropertyID { get; set; }
    
        public virtual Embassy Embassy { get; set; }
        public virtual Property Property { get; set; }
    }
}
