//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalAdmin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RentalEntities : DbContext
    {
        public RentalEntities()
            : base("name=RentalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<AreaRelation> AreaRelations { get; set; }
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<ArticleRelation> ArticleRelations { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<ContactU> ContactUs { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomerBuy> CustomerBuys { get; set; }
        public virtual DbSet<DirectMessage> DirectMessages { get; set; }
        public virtual DbSet<DiscountChange> DiscountChanges { get; set; }
        public virtual DbSet<Email> Emails { get; set; }
        public virtual DbSet<EmailBlock> EmailBlocks { get; set; }
        public virtual DbSet<EmailLayout> EmailLayouts { get; set; }
        public virtual DbSet<EmailMarketingSend> EmailMarketingSends { get; set; }
        public virtual DbSet<EmailSever> EmailSevers { get; set; }
        public virtual DbSet<EmailUnsubscribe> EmailUnsubscribes { get; set; }
        public virtual DbSet<Embassy> Embassies { get; set; }
        public virtual DbSet<Map> Maps { get; set; }
        public virtual DbSet<Metro> Metroes { get; set; }
        public virtual DbSet<PropertyGallery> PropertyGalleries { get; set; }
        public virtual DbSet<PropertyMetro> PropertyMetroes { get; set; }
        public virtual DbSet<PropertyType> PropertyTypes { get; set; }
        public virtual DbSet<SendInEmail> SendInEmails { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Upload> Uploads { get; set; }
        public virtual DbSet<EmbassyProperty> EmbassyProperties { get; set; }
        public virtual DbSet<DisplayLanguage> DisplayLanguages { get; set; }
        public virtual DbSet<BlogType> BlogTypes { get; set; }
        public virtual DbSet<Property> Properties { get; set; }
        public virtual DbSet<ComplexBlog> ComplexBlogs { get; set; }
        public virtual DbSet<RequestApartment> RequestApartments { get; set; }
        public virtual DbSet<Blog> Blogs { get; set; }
    }
}
