//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Property()
        {
            this.ArticleRelations = new HashSet<ArticleRelation>();
            this.EmbassyProperties = new HashSet<EmbassyProperty>();
            this.PropertyGalleries = new HashSet<PropertyGallery>();
            this.PropertyMetroes = new HashSet<PropertyMetro>();
        }
    
        public long PropertyID { get; set; }
        public string PropertyName { get; set; }
        public long PropertyPrice { get; set; }
        public string UserID { get; set; }
        public bool IsExpired { get; set; }
        public System.DateTime InsertDatetime { get; set; }
        public Nullable<int> PropertyTypeID { get; set; }
        public bool IsSpecial { get; set; }
        public string WhyIsSpecial { get; set; }
        public int AreaID { get; set; }
        public int PropertySpace { get; set; }
        public byte PropertyRoom { get; set; }
        public bool PropertyPool { get; set; }
        public int PropertyFloor { get; set; }
        public int PropertyAllFloor { get; set; }
        public byte PropertyAge { get; set; }
        public byte PropertyUnitsPerFloor { get; set; }
        public byte PropertyParkingNumber { get; set; }
        public bool PropertySauna { get; set; }
        public bool PropertyJacuzzi { get; set; }
        public bool PropertyRoofGarden { get; set; }
        public bool PropertyHasLobby { get; set; }
        public bool PropertyHasLobbyMan { get; set; }
        public bool PropertyHasGaurd { get; set; }
        public bool PropertyHasGym { get; set; }
        public Nullable<long> MapID { get; set; }
        public byte PropertyIsFernished { get; set; }
        public int PropertyOurCode { get; set; }
        public string PropertyImageAddress { get; set; }
        public int PropertyOurPoint { get; set; }
        public int PropertyPoint { get; set; }
        public string PropertyDescription { get; set; }
        public int PropetryBathRooms { get; set; }
        public string PropertyWiFi { get; set; }
        public bool PropertyIsShortTerm { get; set; }
        public int PropertyPriceShortDaily { get; set; }
        public int PropertyPriceShortMonthly { get; set; }
        public string PropertyDescriptionAboutOwner { get; set; }
    
        public virtual Area Area { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticleRelation> ArticleRelations { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Map Map { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmbassyProperty> EmbassyProperties { get; set; }
        public virtual PropertyType PropertyType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyGallery> PropertyGalleries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyMetro> PropertyMetroes { get; set; }
    }
}
