//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyGallery
    {
        public long PropertyGalleryID { get; set; }
        public long UploadID { get; set; }
        public System.DateTime PropertyGalleryInsertDate { get; set; }
        public Nullable<long> PropertyID { get; set; }
        public byte PropertyGalleryOrder { get; set; }
        public string GalleryName { get; set; }
    
        public virtual Upload Upload { get; set; }
        public virtual Property Property { get; set; }
    }
}
