//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestApartment
    {
        public long RequestApartmentID { get; set; }
        public string FullName { get; set; }
        public int Beds { get; set; }
        public string AreaName { get; set; }
        public int PersonsCount { get; set; }
        public int MounthCount { get; set; }
        public int DaysCount { get; set; }
        public string WhenCome { get; set; }
        public string Nation { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
    }
}
