//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SendInEmail
    {
        public string SendInEmailTo { get; set; }
        public string SendInEmailSubject { get; set; }
        public string SendInEmailTemplateName { get; set; }
        public bool SendInEmailBulk { get; set; }
        public string SendInEmailUnsubscribeUrl { get; set; }
        public string SendInEmailUserName { get; set; }
        public System.DateTime SendInEmailCreateDate { get; set; }
        public Nullable<System.DateTime> SendInEmailSendDate { get; set; }
        public byte SendInEmailStatus { get; set; }
        public int SendInEmailTry { get; set; }
        public string SendInHtmlContex { get; set; }
        public string SendInTxtContex { get; set; }
        public string UserID { get; set; }
        public bool SendInForceable { get; set; }
        public System.Guid SendinEmailID { get; set; }
        public Nullable<long> EmailServerID { get; set; }
        public long EmailID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Email Email { get; set; }
        public virtual EmailSever EmailSever { get; set; }
    }
}
