//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Upload
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Upload()
        {
            this.Maps = new HashSet<Map>();
            this.Maps1 = new HashSet<Map>();
            this.PropertyGalleries = new HashSet<PropertyGallery>();
        }
    
        public long UploadID { get; set; }
        public string UserName { get; set; }
        public string UploadName { get; set; }
        public byte UploadType { get; set; }
        public string UploadContentType { get; set; }
        public string BasicAddressPhysical { get; set; }
        public string BasicAddressVirtual { get; set; }
        public string UploadAddressOffSet { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public int UploadWidth { get; set; }
        public int UploadHeight { get; set; }
        public int UploadTime { get; set; }
        public long UploadSize { get; set; }
        public bool UploadSourceIsOut { get; set; }
        public bool IsDeleted { get; set; }
        public string UploadWaterMarkName { get; set; }
        public bool UploadIsOptimized { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Map> Maps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Map> Maps1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyGallery> PropertyGalleries { get; set; }
    }
}
